### PR TITLE
NoAppBar

### PR DESCRIPTION
**Pull request by endreman0**
Please check if what you want to add to `beautiful-discord-community/resources` list meets [quality standards](https://github.com/beautiful-discord-community/resources/blob/master/CONTRIBUTING.md#quality-standard) before sending pull request. Thanks!

**Please provide package links to:**
- github.com repo: https://github.com/endreman0/discord-custom ([noappbar.css](https://github.com/endreman0/discord-custom/blob/6f13f8c7b508648304733da3ec071a65c2a8eb9e/noappbar.css))
- embed url: https://cdn.rawgit.com/endreman0/discord-custom/6f13f8c7b508648304733da3ec071a65c2a8eb9e/noappbar.css

**Make sure that you've checked the boxes below before you submit PR:**
- [x] I have added my package in alphabetical order
- [x] I know that this package was not listed before
- [x] I have added @import compatible link (ex. [rawgit.com](https://rawgit.com)) to the repo and to my pull request
- [x] I have read [Contribution guidelines](https://github.com/beautiful-discord-community/resources/blob/master/CONTRIBUTING.md#contribution-guidelines).

Thanks for your PR, you're awesome! :+1:

Three additional questions:
1. It doesn't look like the quality standard exists in CONTRIBUTING.md, and of the three commits that affect the file, none of them adds or removes that section. Is that standard available elsewhere?
1. This PR adds my snippet, and also moves Draco712's to the appropriate spot in the list. Should I revert that and create a separate PR, or leave it in this one?
1. Is a cdn.rawgit.com link with a commit hash (what I have now) preferable to a rawgit.com link on master, or vice versa?

### CODE REVIEW

**Comment by TriggerRimfire** [comment]
You might want to use different selectors for these type of classes (winButtonMinMax-bT_gQ1) etc as these are generated by React and change every update.

To answer your questions, 1. It's a "as long as its neat its ok i guess" type of thing, we're not too strict about it. 2, that's fine. 3, with commit hash is preferred.

**Comment by TriggerRimfire** [comment]
@zet4 merge?

**Comment by endreman0** [comment]
I can clean up those React-generated selectors before merge. So avoid selectors with random alphanumerics in them?

**Comment by TriggerRimfire** [comment]
Yes, child selectors or using the [prop=*] selectors is preferred.

**Pull request merged**
